import type {
  Auditoria,
  NaoConformidade,
  PlanoAcao,
  TemplateAuditoria,
  Usuario,
} from "./types";

/* ---------------------------------------------------------------------------
   Dados de demonstração.
   Camada isolada de propósito: a UI consome apenas as funções `obter*` deste
   módulo, então a troca por consultas reais ao Supabase não toca nos componentes.
--------------------------------------------------------------------------- */

export const usuarios: Usuario[] = [
  {
    id: "u1",
    nome: "Renata Dealz",
    email: "renata.dealz@empresa.com.br",
    papel: "gestor",
    cargo: "Gestora da Qualidade",
    avatarCor: "#4f46e5",
  },
  {
    id: "u2",
    nome: "Marcos Antunes",
    email: "marcos.antunes@empresa.com.br",
    papel: "auditor_lider",
    cargo: "Auditor Líder",
    avatarCor: "#0d9488",
  },
  {
    id: "u3",
    nome: "Juliana Prado",
    email: "juliana.prado@empresa.com.br",
    papel: "auditor",
    cargo: "Analista da Qualidade",
    avatarCor: "#b45309",
  },
  {
    id: "u4",
    nome: "Carlos Nogueira",
    email: "carlos.nogueira@empresa.com.br",
    papel: "auditado",
    cargo: "Supervisor de Produção",
    avatarCor: "#be123c",
  },
  {
    id: "u5",
    nome: "Fernanda Lima",
    email: "fernanda.lima@empresa.com.br",
    papel: "auditado",
    cargo: "Coordenadora de Suprimentos",
    avatarCor: "#7c3aed",
  },
  {
    id: "u6",
    nome: "Diego Ramos",
    email: "diego.ramos@empresa.com.br",
    papel: "auditor",
    cargo: "Auditor Interno",
    avatarCor: "#0369a1",
  },
];

export const templates: TemplateAuditoria[] = [
  {
    id: "t1",
    nome: "Auditoria Interna — ISO 9001:2015 (completa)",
    norma: "ISO 9001:2015",
    versao: "3.2",
    descricao:
      "Checklist integral do Sistema de Gestão da Qualidade, cobrindo as cláusulas 4 a 10 da norma.",
    ativo: true,
    atualizadoEm: "2026-05-12",
    secoes: [
      {
        id: "s1",
        titulo: "Contexto da organização",
        clausula: "4",
        perguntas: [
          {
            id: "p1",
            ordem: 1,
            texto:
              "A organização determinou as questões internas e externas pertinentes ao seu propósito?",
            requisito: { clausula: "4.1", titulo: "Entendendo a organização e seu contexto" },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
            orientacao: "Verificar análise SWOT, atas de análise crítica ou matriz de contexto.",
          },
          {
            id: "p2",
            ordem: 2,
            texto:
              "As partes interessadas pertinentes e seus requisitos foram identificados e monitorados?",
            requisito: {
              clausula: "4.2",
              titulo: "Necessidades e expectativas de partes interessadas",
            },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
          },
          {
            id: "p3",
            ordem: 3,
            texto: "O escopo do SGQ está documentado, disponível e mantido atualizado?",
            requisito: { clausula: "4.3", titulo: "Escopo do sistema de gestão da qualidade" },
            tipoResposta: "conformidade",
            peso: 2,
            exigeEvidencia: true,
          },
        ],
      },
      {
        id: "s2",
        titulo: "Liderança",
        clausula: "5",
        perguntas: [
          {
            id: "p4",
            ordem: 1,
            texto:
              "A alta direção demonstra liderança e comprometimento com o SGQ e com o foco no cliente?",
            requisito: { clausula: "5.1", titulo: "Liderança e comprometimento" },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
          },
          {
            id: "p5",
            ordem: 2,
            texto: "A política da qualidade está estabelecida, comunicada e compreendida?",
            requisito: { clausula: "5.2", titulo: "Política da qualidade" },
            tipoResposta: "conformidade",
            peso: 2,
            exigeEvidencia: true,
          },
          {
            id: "p6",
            ordem: 3,
            texto:
              "As responsabilidades e autoridades pertinentes estão atribuídas e comunicadas?",
            requisito: { clausula: "5.3", titulo: "Funções, responsabilidades e autoridades" },
            tipoResposta: "conformidade",
            peso: 2,
            exigeEvidencia: false,
          },
        ],
      },
      {
        id: "s3",
        titulo: "Operação",
        clausula: "8",
        perguntas: [
          {
            id: "p7",
            ordem: 1,
            texto:
              "Os critérios para avaliação, seleção e monitoramento de fornecedores externos estão definidos e aplicados?",
            requisito: { clausula: "8.4", titulo: "Controle de processos providos externamente" },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
            orientacao:
              "Solicitar registros de qualificação e a última avaliação de desempenho de fornecedores críticos.",
          },
          {
            id: "p8",
            ordem: 2,
            texto: "A produção é realizada sob condições controladas e com rastreabilidade?",
            requisito: { clausula: "8.5", titulo: "Produção e provisão de serviço" },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
          },
          {
            id: "p9",
            ordem: 3,
            texto: "As saídas não conformes são identificadas, segregadas e tratadas?",
            requisito: { clausula: "8.7", titulo: "Controle de saídas não conformes" },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
          },
        ],
      },
      {
        id: "s4",
        titulo: "Avaliação de desempenho e melhoria",
        clausula: "9 e 10",
        perguntas: [
          {
            id: "p10",
            ordem: 1,
            texto: "A satisfação do cliente é monitorada e analisada criticamente?",
            requisito: { clausula: "9.1.2", titulo: "Satisfação do cliente" },
            tipoResposta: "conformidade",
            peso: 2,
            exigeEvidencia: true,
          },
          {
            id: "p11",
            ordem: 2,
            texto: "O programa de auditoria interna é executado conforme planejado?",
            requisito: { clausula: "9.2", titulo: "Auditoria interna" },
            tipoResposta: "conformidade",
            peso: 2,
            exigeEvidencia: true,
          },
          {
            id: "p12",
            ordem: 3,
            texto:
              "As não-conformidades são tratadas com análise de causa e verificação de eficácia?",
            requisito: { clausula: "10.2", titulo: "Não conformidade e ação corretiva" },
            tipoResposta: "conformidade",
            peso: 3,
            exigeEvidencia: true,
          },
        ],
      },
    ],
  },
  {
    id: "t2",
    nome: "Auditoria de Processo — Produção",
    norma: "ISO 9001:2015",
    versao: "1.4",
    descricao: "Checklist reduzido focado nas cláusulas 8.5 e 8.7, para inspeções de chão de fábrica.",
    ativo: true,
    atualizadoEm: "2026-03-28",
    secoes: [],
  },
  {
    id: "t3",
    nome: "Auditoria de Fornecedor",
    norma: "ISO 9001:2015",
    versao: "2.0",
    descricao: "Avaliação de fornecedores críticos conforme cláusula 8.4.",
    ativo: false,
    atualizadoEm: "2025-11-05",
    secoes: [],
  },
];

export const auditorias: Auditoria[] = [
  {
    id: "a1",
    codigo: "AUD-2026-014",
    titulo: "Auditoria Interna do SGQ — Produção",
    escopo: "Processos produtivos da linha 2, incluindo controle de saídas não conformes.",
    processoAuditado: "Produção",
    unidade: "Planta Sul — Joinville",
    templateId: "t1",
    norma: "ISO 9001:2015",
    status: "em_execucao",
    dataPlanejada: "2026-08-17",
    dataInicio: "2026-08-17",
    auditorLiderId: "u2",
    auditoresIds: ["u3", "u6"],
    responsavelAreaId: "u4",
    indiceConformidade: 78.5,
    totalPerguntas: 12,
    perguntasRespondidas: 9,
  },
  {
    id: "a2",
    codigo: "AUD-2026-013",
    titulo: "Auditoria de Fornecedor — Metalúrgica Vetor",
    escopo: "Qualificação anual de fornecedor crítico de componentes usinados.",
    processoAuditado: "Suprimentos",
    unidade: "Fornecedor externo",
    templateId: "t3",
    norma: "ISO 9001:2015",
    status: "em_relatorio",
    dataPlanejada: "2026-08-04",
    dataInicio: "2026-08-04",
    auditorLiderId: "u2",
    auditoresIds: ["u3"],
    responsavelAreaId: "u5",
    indiceConformidade: 86.2,
    totalPerguntas: 18,
    perguntasRespondidas: 18,
  },
  {
    id: "a3",
    codigo: "AUD-2026-012",
    titulo: "Auditoria Interna do SGQ — Suprimentos",
    escopo: "Cláusula 8.4 — controle de processos, produtos e serviços providos externamente.",
    processoAuditado: "Suprimentos",
    unidade: "Matriz — Curitiba",
    templateId: "t1",
    norma: "ISO 9001:2015",
    status: "concluida",
    dataPlanejada: "2026-07-14",
    dataInicio: "2026-07-14",
    dataConclusao: "2026-07-22",
    auditorLiderId: "u6",
    auditoresIds: ["u3"],
    responsavelAreaId: "u5",
    indiceConformidade: 92.4,
    totalPerguntas: 12,
    perguntasRespondidas: 12,
  },
  {
    id: "a4",
    codigo: "AUD-2026-011",
    titulo: "Auditoria Interna do SGQ — Comercial",
    escopo: "Requisitos para produtos e serviços e satisfação do cliente.",
    processoAuditado: "Comercial",
    unidade: "Matriz — Curitiba",
    templateId: "t1",
    norma: "ISO 9001:2015",
    status: "concluida",
    dataPlanejada: "2026-06-09",
    dataInicio: "2026-06-09",
    dataConclusao: "2026-06-16",
    auditorLiderId: "u2",
    auditoresIds: ["u6"],
    responsavelAreaId: "u1",
    indiceConformidade: 95.8,
    totalPerguntas: 12,
    perguntasRespondidas: 12,
  },
  {
    id: "a5",
    codigo: "AUD-2026-015",
    titulo: "Auditoria Interna do SGQ — Manutenção",
    escopo: "Infraestrutura, recursos de monitoramento e medição.",
    processoAuditado: "Manutenção",
    unidade: "Planta Sul — Joinville",
    templateId: "t1",
    norma: "ISO 9001:2015",
    status: "planejada",
    dataPlanejada: "2026-09-08",
    auditorLiderId: "u6",
    auditoresIds: ["u3"],
    responsavelAreaId: "u4",
    indiceConformidade: 0,
    totalPerguntas: 12,
    perguntasRespondidas: 0,
  },
  {
    id: "a6",
    codigo: "AUD-2026-016",
    titulo: "Auditoria Interna do SGQ — Recursos Humanos",
    escopo: "Competência, conscientização e comunicação.",
    processoAuditado: "Recursos Humanos",
    unidade: "Matriz — Curitiba",
    templateId: "t1",
    norma: "ISO 9001:2015",
    status: "planejada",
    dataPlanejada: "2026-09-22",
    auditorLiderId: "u2",
    auditoresIds: ["u6"],
    responsavelAreaId: "u1",
    indiceConformidade: 0,
    totalPerguntas: 12,
    perguntasRespondidas: 0,
  },
];

export const naoConformidades: NaoConformidade[] = [
  {
    id: "nc1",
    codigo: "NC-2026-041",
    auditoriaId: "a1",
    perguntaId: "p9",
    requisito: { clausula: "8.7", titulo: "Controle de saídas não conformes" },
    tipo: "nc_maior",
    descricao:
      "Peças reprovadas na inspeção final permanecem na área de expedição sem identificação nem segregação física.",
    evidenciaObjetiva:
      "Constatadas 34 peças do lote L-2261 em pallet junto ao material aprovado, sem etiqueta de bloqueio. Registro fotográfico EV-118.",
    status: "em_execucao",
    responsavelId: "u4",
    abertaEm: "2026-08-17",
    prazo: "2026-09-15",
    causaRaiz:
      "Ausência de área demarcada para bloqueio na expedição após a realocação do layout em maio/2026.",
    metodoAnaliseCausa: "5_porques",
  },
  {
    id: "nc2",
    codigo: "NC-2026-040",
    auditoriaId: "a1",
    perguntaId: "p8",
    requisito: { clausula: "8.5", titulo: "Produção e provisão de serviço" },
    tipo: "nc_menor",
    descricao:
      "Duas fichas de processo da linha 2 estavam em revisão desatualizada no posto de trabalho.",
    evidenciaObjetiva:
      "FP-204 rev.3 e FP-209 rev.2 em uso; revisões vigentes são rev.5 e rev.4 respectivamente.",
    status: "acao_definida",
    responsavelId: "u4",
    abertaEm: "2026-08-17",
    prazo: "2026-09-01",
    causaRaiz: "Falha na rotina de recolhimento de documentos obsoletos após revisão.",
    metodoAnaliseCausa: "5_porques",
  },
  {
    id: "nc3",
    codigo: "NC-2026-039",
    auditoriaId: "a2",
    requisito: { clausula: "8.4", titulo: "Controle de processos providos externamente" },
    tipo: "nc_menor",
    descricao:
      "O fornecedor não apresentou registros de calibração de dois instrumentos utilizados na inspeção de recebimento.",
    evidenciaObjetiva: "Paquímetros PQ-07 e PQ-11 sem certificado válido desde 03/2026.",
    status: "aguardando_verificacao",
    responsavelId: "u5",
    abertaEm: "2026-08-05",
    prazo: "2026-08-28",
    causaRaiz: "Contrato de calibração vencido e não renovado a tempo.",
    metodoAnaliseCausa: "5w2h",
  },
  {
    id: "nc4",
    codigo: "NC-2026-035",
    auditoriaId: "a3",
    requisito: { clausula: "8.4", titulo: "Controle de processos providos externamente" },
    tipo: "observacao",
    descricao:
      "A matriz de criticidade de fornecedores não foi revisada após a inclusão de três novos itens em 2026.",
    evidenciaObjetiva: "Última revisão da matriz datada de 11/2025.",
    status: "encerrada_eficaz",
    responsavelId: "u5",
    abertaEm: "2026-07-16",
    prazo: "2026-08-10",
    encerradaEm: "2026-08-06",
  },
  {
    id: "nc5",
    codigo: "NC-2026-034",
    auditoriaId: "a3",
    requisito: { clausula: "9.1.2", titulo: "Satisfação do cliente" },
    tipo: "nc_menor",
    descricao:
      "Pesquisa de satisfação do 1º semestre aplicada sem análise crítica documentada dos resultados.",
    evidenciaObjetiva: "Resultados consolidados em planilha, sem ata de análise crítica associada.",
    status: "aberta",
    responsavelId: "u1",
    abertaEm: "2026-07-18",
    prazo: "2026-08-14",
  },
  {
    id: "nc6",
    codigo: "NC-2026-030",
    auditoriaId: "a4",
    requisito: { clausula: "5.2", titulo: "Política da qualidade" },
    tipo: "observacao",
    descricao:
      "Parte da equipe comercial admitida em 2026 desconhece o conteúdo da política da qualidade.",
    evidenciaObjetiva: "Entrevista com 4 colaboradores; 3 não souberam citar os compromissos.",
    status: "encerrada_eficaz",
    responsavelId: "u1",
    abertaEm: "2026-06-12",
    prazo: "2026-07-10",
    encerradaEm: "2026-07-08",
  },
  {
    id: "nc7",
    codigo: "NC-2026-028",
    auditoriaId: "a4",
    requisito: { clausula: "10.2", titulo: "Não conformidade e ação corretiva" },
    tipo: "nc_maior",
    descricao:
      "Ações corretivas de 2025 encerradas sem registro da verificação de eficácia exigida pela cláusula 10.2.",
    evidenciaObjetiva: "5 das 9 ações encerradas no período sem campo de eficácia preenchido.",
    status: "encerrada_ineficaz",
    responsavelId: "u1",
    abertaEm: "2026-06-10",
    prazo: "2026-07-20",
    encerradaEm: "2026-07-25",
  },
];

export const planosAcao: PlanoAcao[] = [
  {
    id: "pa1",
    codigo: "PA-2026-041",
    naoConformidadeId: "nc1",
    oQue: "Implantar área de bloqueio demarcada e identificada na expedição.",
    porQue:
      "Impedir que material não conforme seja expedido, atendendo à cláusula 8.7 da ISO 9001.",
    onde: "Planta Sul — Joinville, expedição",
    quando: "2026-09-15",
    quem: "Carlos Nogueira",
    responsavelId: "u4",
    como: "Demarcação com sinalização de solo, gaiola vermelha identificada e revisão do PO-EXP-04.",
    quantoCusta: 4800,
    status: "em_andamento",
    progresso: 60,
    criadoEm: "2026-08-18",
  },
  {
    id: "pa2",
    codigo: "PA-2026-040",
    naoConformidadeId: "nc2",
    oQue: "Recolher documentos obsoletos e implantar checagem semanal de revisões nos postos.",
    porQue: "Garantir que apenas revisões vigentes sejam utilizadas na produção.",
    onde: "Linha 2 — Planta Sul",
    quando: "2026-09-01",
    quem: "Carlos Nogueira",
    responsavelId: "u4",
    como: "Varredura dos 14 postos, substituição das fichas e inclusão do item no checklist do líder de turno.",
    status: "pendente",
    progresso: 0,
    criadoEm: "2026-08-18",
  },
  {
    id: "pa3",
    codigo: "PA-2026-039",
    naoConformidadeId: "nc3",
    oQue: "Renovar o contrato de calibração e recalibrar os instrumentos afetados.",
    porQue: "Assegurar rastreabilidade metrológica das medições de recebimento.",
    onde: "Fornecedor Metalúrgica Vetor",
    quando: "2026-08-28",
    quem: "Fernanda Lima",
    responsavelId: "u5",
    como: "Contratação de laboratório RBC e envio dos paquímetros PQ-07 e PQ-11.",
    quantoCusta: 1250,
    status: "concluida",
    progresso: 100,
    criadoEm: "2026-08-06",
    concluidoEm: "2026-08-21",
  },
  {
    id: "pa4",
    codigo: "PA-2026-034",
    naoConformidadeId: "nc5",
    oQue: "Realizar análise crítica documentada da pesquisa de satisfação.",
    porQue: "Atender à cláusula 9.1.2 e gerar entradas para a análise crítica pela direção.",
    onde: "Matriz — Curitiba",
    quando: "2026-08-14",
    quem: "Renata Dealz",
    responsavelId: "u1",
    como: "Reunião com comercial e qualidade, com ata registrando conclusões e ações.",
    status: "atrasada",
    progresso: 25,
    criadoEm: "2026-07-20",
  },
  {
    id: "pa5",
    codigo: "PA-2026-035",
    naoConformidadeId: "nc4",
    oQue: "Revisar a matriz de criticidade de fornecedores.",
    porQue: "Manter os critérios de controle proporcionais ao risco de cada fornecedor.",
    onde: "Matriz — Curitiba",
    quando: "2026-08-10",
    quem: "Fernanda Lima",
    responsavelId: "u5",
    como: "Reclassificação dos 3 novos itens e aprovação da matriz revisada.",
    status: "concluida",
    progresso: 100,
    criadoEm: "2026-07-17",
    concluidoEm: "2026-08-05",
    eficaciaVerificada: true,
    observacaoEficacia:
      "Matriz rev.4 aprovada em 05/08/2026; amostragem confirmou reclassificação correta.",
  },
];

/** Série histórica do índice de conformidade, alimentada pelas auditorias encerradas. */
export const historicoConformidade = [
  { mes: "Mar", indice: 88.1, meta: 90 },
  { mes: "Abr", indice: 89.6, meta: 90 },
  { mes: "Mai", indice: 91.2, meta: 90 },
  { mes: "Jun", indice: 95.8, meta: 90 },
  { mes: "Jul", indice: 92.4, meta: 90 },
  { mes: "Ago", indice: 82.4, meta: 90 },
];

export const ncPorProcesso = [
  { processo: "Produção", maior: 1, menor: 1, observacao: 0 },
  { processo: "Suprimentos", maior: 0, menor: 1, observacao: 1 },
  { processo: "Comercial", maior: 1, menor: 0, observacao: 1 },
  { processo: "Manutenção", maior: 0, menor: 0, observacao: 0 },
  { processo: "RH", maior: 0, menor: 0, observacao: 0 },
];
